---
name: perlcritic
on: [push, pull_request]

jobs:
  perlcritic_checks:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/containers/os-autoinst_dev
    steps:
      - uses: actions/checkout@v4
      - name: Static analysis
        run: |
          git config --global --add safe.directory '*'
          ./external/os-autoinst-common/tools/perlcritic --quiet $(git ls-files -- '*.p[ml]')
